### ISSUE TITLE
Add Contributor's List in Readme.

### ISSUE THREAD

**Issue by noviicee** [noviicee/Banque-De-Questions#25]
There are many contributors to an open source project.
It is always a good idea to give our contributors a shout-out.  :tada: 

We would be happy to include a list of contributors who have been contributing to this project. :gift_heart: 
**The task is to add a list of contributors (in a clean, concise, and attractive way) to the Readme of the project.**

**Additional context**
A simple start can be considered, but
It will be a bonus if the whole process can be automated. :+1: :star:

**Comment by donheshanthaka** [comment]
Hey there, can i participate in this too? i can fully automate this process.

**Comment by aswin2108** [comment]
hey @donheshanthaka I am already on it! Hope you would find another! :)
